joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 1000

flywheel_controller:
  type: "effort_controllers/JointEffortController"
  joint: arm_to_flywheel

arm_spring:
  type: "effort_controllers/JointPositionController"
  joint: arm_spring
  pid: { p: 385.0, i: 0.0001, d: 0.0001 }

arm_controller:
  type: "effort_controllers/JointEffortController"
  joint: arm_prism
  # pid: { p: 500, i: 0.1, d: 5 }
