joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

flywheel_controller:
  type: "effort_controllers/JointEffortController"
  joint: arm_to_flywheel

arm_controller:
  type: "effort_controllers/JointEffortController"
  joint: arm_prism
  # pid: { p: 10, i: 0.01, d: 3 }
