joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

flywheel_controller:
  type: "effort_controllers/JointEffortController"
  joint: arm_to_flywheel

arm_controller:
  type: "effort_controllers/JointPositionController"
  joint: arm_prism
  pid: { p: 500, i: 0.1, d: 5 }
